package Modelo;
// Generated 5/11/2016 10:46:56 AM by Hibernate Tools 3.6.0


import java.io.Serializable;

/**
 * Dulces generated by hbm2java
 */
public class Dulces  implements java.io.Serializable {


     private int idDulce;
     private String nombreDulce;
     private Integer cantidadDulce;

    public Dulces() {
    }

	
    public Dulces(int idDulce) {
        this.idDulce = idDulce;
    }
    public Dulces(int idDulce, String nombreDulce, Integer cantidadDulce) {
       this.idDulce = idDulce;
       this.nombreDulce = nombreDulce;
       this.cantidadDulce = cantidadDulce;
    }
   
    public int getIdDulce() {
        return this.idDulce;
    }
    
    public void setIdDulce(int idDulce) {
        this.idDulce = idDulce;
    }
    public String getNombreDulce() {
        return this.nombreDulce;
    }
    
    public void setNombreDulce(String nombreDulce) {
        this.nombreDulce = nombreDulce;
    }
    public Integer getCantidadDulce() {
        return this.cantidadDulce;
    }
    
    public void setCantidadDulce(Integer cantidadDulce) {
        this.cantidadDulce = cantidadDulce;
    }




}


